### ISSUE TITLE
issue with imbalanced data

### ISSUE THREAD

**Issue by Emadeldeen-24** [kmkurn/pytorch-crf#58]
Firstly, thank you for sharing the code and making it easy to use.
I'm using CRF to classify EEG data, as the labels are sequential and having dependencies.

However, the labels are imbalanced and CRF seems to just produce the labels of the majority class.
The use of oversamling is not proper in this case, so I wonder if you may have a solution or suggestion for this issue.

Thanks.

**Comment by kmkurn** [comment]
Hi, no worries.

I think the issue of imbalanced data also happens in part-of-speech tagging where most words are nouns. I'm not sure if people handle this issue in POS tagging because in reality, nouns are indeed very common. What I would suggest is:

1. use a more powerful model for the emission score, because I think that's where you can truly improve, as opposed to the transition probabilities which are just categorical distributions, or
1. use more complex transition distribution, in which case you must use another library e.g. [pytorch-struct](http://nlp.seas.harvard.edu/pytorch-struct) that offers you more freedom in specifying the emission/transition score.

**Comment by Emadeldeen-24** [comment]
Thank you for your quick reply.
- For the first suggestion, I really tried multiple models and all end with the same result.
- I will check the second suggestion.

But I have another question: isn't there any parameters or things to tune in the CRF model itself?
Thanks
