### ISSUE TITLE
Torch jit script failed 

### ISSUE THREAD

**Issue by changshivek** [kmkurn/pytorch-crf#93]
Hi there,

Thank you for the good module!
I am using the module on a project which needs to transfer the saved model to jit script format, but it seems jit scripting doesn't work on the module.
I found a closed issue mentioned about jit tracing and scripting on the module, in issue #79 @erksch said he somehow managed to make the module scriptable and made a PR, but I could find the PR in the PR list whether open or closed.
May I ask if there is any solution to make this module jit scriptable? For I found the module handy and efficient, I want to use it in my project.

Best regards, 
Liu

**Comment by kmkurn** [comment]
Hi, thanks for the kind words! Unfortunately, I've never dealt with jit so I'm afraid I can't really help you here. I'm not planning on supporting it any time soon either (unless someone makes a PR 😉) so I'm closing this issue.

**Comment by erksch** [comment]
Hey @changshivek!

Yes, I have a working version but I never came around to make a PR because it would break the interface of the module.
Nevertheless I just created a fork that includes the changes on https://github.com/erksch/pytorch-crf/tree/jit-scriptable.
I did cut some corners (removing validate step and mask), but it works (I also ran some of the tests) and I have used it in production systems for some time.
